kind: Service
apiVersion: v1
metadata:
  name: spring-petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
  - protocol: TCP
    port: $PORT
    targetPort: 8080
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deployment
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
