kind: Service
apiVersion: v1
metadata:
  name: spring-petclinic-service-QA
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic-QA
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEP_NAME
  labels:
    app: spring-petclinic-QA
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic-QA
  template:
    metadata:
      labels:
        app: spring-petclinic-QA
    spec:
      containers:
      - name: spring-petclinic-QA
        image: $DOCKER_IMAGE_NAME:5
        ports:
        - containerPort: 8080
